apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - role: controller+worker
    os: arch
    ssh:
      address: 192.168.8.2
      user: alan
      keyPath: ~/.ssh/ssh_keys/id_home_k8s
  - role: worker
    installFlags:
    ssh:
      address: 192.168.8.20
      user: alan
  - role: worker
    ssh:
      address: 192.168.8.21
      user: alan
  # - role: worker
  #   ssh:
  #     address: 192.168.8.20
  #     user: alan
  k0s:
    version: v1.22.2+k0s.1
